### PR TITLE
Dark Mode Added

### LINKED ISSUE #71: Dark Theme UI
### Is your feature request related to a problem? Please describe.
Switchable dark theme UI

### Describe the solution you'd like
add toggle to switch between dark and light theme

### Describe how this feature will be useful to our readers
less eye strain

### Additional context
pure javascript implementation

### PR DESCRIPTION
**Pull request by arpit456jain**
Added the dark mode to the website.

Closes: #71

I am attaching a video for better understanding my changes

https://user-images.githubusercontent.com/55352601/112534471-1d0cee00-8dd1-11eb-8ac2-9a9af22d343f.mp4

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Code style update (formatting, local variables)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [] Any dependent changes have been merged and published in downstream modules.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by arpit456jain** [comment]
@vigneshshettyin sir I don't understand why this is showing error. Please help.

**Comment by vigneshshettyin** [comment]
Kindly remove the unused function (https://www.codefactor.io/repository/github/vigneshshettyin/flask-generate-certificate/pull/104). I would suggest you use a toggle button to switch between dark mode and light mode. Also, the login, forgot, & register page needs some design changes I feel so. @arpit456jain

**Comment by arpit456jain** [comment]
> Kindly remove the unused function (https://www.codefactor.io/repository/github/vigneshshettyin/flask-generate-certificate/pull/104). I would suggest you use a toggle button to switch between dark mode and light mode. Also, the login, forgot, & register page needs some design changes I feel so. @arpit456jain

ok sir let me this..
And sir I will surely work on design the login, forgot, & register page as soon as possible but for that I will create a new issue .
I had already contribute 2 times in this projects . this is my 3rd time , and I would love to contribute more in future.

**Comment by vigneshshettyin** [comment]
> > Kindly remove the unused function (https://www.codefactor.io/repository/github/vigneshshettyin/flask-generate-certificate/pull/104). I would suggest you use a toggle button to switch between dark mode and light mode. Also, the login, forgot, & register page needs some design changes I feel so. @arpit456jain
> 
> ok sir let me this..
> And sir I will surely work on design the login, forgot, & register page as soon as possible but for that I will create a new issue .
> I had already contribute 2 times in this projects . this is my 3rd time , and I would love to contribute more in future.

Okay, Great! @arpit456jain

**Comment by arpit456jain** [comment]
sir please let me change button to a tag again should i create a new issue it just take 2 min

**Comment by vigneshshettyin** [comment]
Yup, Create a new issue @arpit456jain

**Comment by arpit456jain** [comment]
flask

**Comment by arpit456jain** [comment]
ok sir just 1min

**Pull request merged**
