### PR TITLE
[Gssoc21] Added the dark mode in dashboard

### LINKED ISSUE #236: [Gssoc'21] Adding dark mode in dashboard
### Is your feature request related to a problem? Please describe.
I would like to add the dark mode in dashboard 

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 
dark mode is not available in dashboard

Closes: #236 

### Describe the changes you've made

dd

## Type of change

What sort of change have you made:

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Code style update (formatting, local variables)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [] Any dependent changes have been merged and published in downstream modules.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by arpit456jain** [comment]
dd in flask

There is not enough space in mobile view for toggle button so it is looking like this.
If its not ok then i will remove toggle button in mobile view

**Comment by arpit456jain** [comment]
dd 2

@vigneshshettyin I had tried a lot and finally it looking like this i hope its fine

**Review by shades-7 — APPROVED** [review]
Well done 🏆

**Comment by arpit456jain** [comment]
@shades-7 can you please add suitable labels to it

**Comment by arpit456jain** [comment]
@vigneshshettyin i had solved the problem you had raised
final

**Pull request merged**
