### PR TITLE
Added Facebook Login

### LINKED ISSUE #86: Social login With Facebook
### Is your feature request related to a probllem?
As Facebook is mentioned in UI , so authentication also be implemented using Facebook

### Which Program are you part of?
- [x] GSSOC21

### PR DESCRIPTION
**Pull request by Sukriti-sood**
Info about the related issue
Closes: #86 

Describe the changes you've made
Give a clear description what modifications you have made

Integrated Facebook Sign for users to login with google

Type of change
What sort of change have you made:

[] Bug fix (non-breaking change which fixes an issue)
 New feature (non-breaking change which adds functionality)
[] Code style update (formatting, local variables)
[] Breaking change (fix or feature that would cause existing functionality to not work as expected)
[] This change requires a documentation update
Mention any unusual behavior of your code (Write NA if not)
Any unusual behavior of your code

Checklist:
 [] My code follows the guidelines of this project.
 [] I have performed a self-review of my own code.
 [] I have commented on my code, particularly wherever it was hard to understand.
 [] My changes generate no new warnings.

Success Status is Shown while making request for Facebook Login

Screenshot from 2021-03-30 14-40-53

Due to unsecured Connection( With Local host , It stop )

Screenshot from 2021-03-30 15-39-50

### CODE REVIEW

**Comment by shades-7** [comment]
> Close Issue
> #86

hello @Sukriti-sood please edit the description of your PR on the basics of PR template. and also provide the screenshot of changes in the website.

**Comment by Sukriti-sood** [comment]
> > Close Issue
> > #86
> 
> hello @Sukriti-sood please edit the description of your PR on the basics of PR template. and also provide the screenshot of changes in the website.

I have edited the description

**Review by shades-7 — COMMENTED** [review]
@vigneshshettyin have a look once.

**Review by rexdivakar — APPROVED** [review]

**Comment by rexdivakar** [comment]
Everything looks good @vigneshshettyin  we can approve it !

**Comment by Sukriti-sood** [comment]
@vigneshshettyin  Please add labels to this Pr.

**Pull request merged**
