### PR TITLE
EnhanceMent  in show pasword feature in login/signup

### LINKED ISSUE #338: Enhacement in show password
Enhacement in show password 
eye

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

EnhanceMent  in show pasword feature in login/signup

Closes: #338 

### Describe the changes you've made

https://user-images.githubusercontent.com/55352601/117150713-05fceb00-add6-11eb-9a24-9276ab314183.mp4

## Type of change

What sort of change have you made:

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Code style update (formatting, local variables)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [] My changes generate no new warnings.
- [] Any dependent changes have been merged and published in downstream modules.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by arpit456jain** [comment]
@vigneshshettyin i had added this feature in both login and sign up pages under this PR kindly review my PR

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin i had added this feature in both login and sign up pages under this PR kindly review my PR

Hey, one correction for register page don't add it for both the input fields @arpit456jain it doesn't look good.

**Comment by arpit456jain** [comment]
> > @vigneshshettyin i had added this feature in both login and sign up pages under this PR kindly review my PR
> 
> Hey, one correction for register page don't add it for both the input fields @arpit456jain it doesn't look good.

Then should i revert changes in register page like previously show password check box or 

Should i add the eye icon in only one field?

**Comment by vigneshshettyin** [comment]
> > > @vigneshshettyin i had added this feature in both login and sign up pages under this PR kindly review my PR
> > 
> > Hey, one correction for register page don't add it for both the input fields @arpit456jain it doesn't look good.
> 
> Then should i revert changes in register page like previously show password check box

No issues let it be there @arpit456jain

**Pull request merged**
