### PR TITLE
Change button to tag

### LINKED ISSUE #112: Gssoc'21 Change button to a tag again
### **Describe the bug**
Changing button to a tag again
### Which Program are you part of?

- [] GSSOC21
- [] Any other

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

- Info about the related issue 

Closes: #112 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Code style update (formatting, local variables)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [] Any dependent changes have been merged and published in downstream modules.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by arpit456jain** [comment]
@vigneshshettyin done sir now its fine.

**Comment by vigneshshettyin** [comment]
Hey, @arpit456jain Can you upload a screenshot of the change which you have done.

**Comment by arpit456jain** [comment]
yes sir ofcourse. 1 min

**Comment by arpit456jain** [comment]
when I changes a tag to button it was looking some thing like this.
flask
now I revert button to a tag again so its looking now like this

https://user-images.githubusercontent.com/55352601/112585354-a64b1180-8e1f-11eb-9fe4-67e26d543c42.mp4

**Comment by arpit456jain** [comment]
@vigneshshettyin sir please add labels of gssoc'21 before merging

**Comment by vigneshshettyin** [comment]
> when I changes a tag to button it was looking some thing like this.
> flask
> now I revert button to a tag again so its looking now like this
> 
>  2021-03-26.10-36-26.mp4

Hey, @arpit456jain that button is very basic. Have some modern toggle buttons something like this ( https://codepen.io/lerida/pen/ZEbWBjp). I'll be closing this pr create a new pr.

**Comment by arpit456jain** [comment]
> > when I changes a tag to button it was looking some thing like this.
> > flask
> > now I revert button to a tag again so its looking now like this
> > 2021-03-26.10-36-26.mp4
> 
> Hey, @arpit456jain that button is very basic. Have some modern toggle buttons something like this ( https://codepen.io/lerida/pen/ZEbWBjp). I'll be closing this pr create a new pr.

yes sir I agree I have create This PR only for changing that button because its looking very odd .
For now if it is  a tag It will now look odd .
I will try to make a cool toggle button but for now it should be in a tag otherwise it looks odd in the page.
Please watch the video attached above after a tag it is ok for now.

**Comment by vigneshshettyin** [comment]
Okay, I'll approve for now. But work on changing the button.

**Comment by arpit456jain** [comment]
yes sir sure

**Comment by vigneshshettyin** [comment]
@all-contributors please add @arpit456jain  for code and design

**Pull request merged**
