### PR TITLE
[Gssoc'21] Fix the decrease the size of toggle button

### LINKED ISSUE #158: [Gssoc'21] Size of dark mode toggle is too big
### **Describe the bug**
Size of dark mode toggle is too big
### **Expected behavior**
Its size should be decrease little bit in Desktop view and little bit more for phone view

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 
The size of toggle button was very big.
I was looking like this.
togle prev

Closes: #158 

### Describe the changes you've made
I had decrease the size of toggle button as much as possible.
I had create a separate CSS file for dark-mode named as darkmode.css
for all the pages otherwise I have to make changes in every file every time.
 now It is looking like this.
toggle new

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Code style update (formatting, local variables)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [] Any dependent changes have been merged and published in downstream modules.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by arpit456jain** [comment]
@vigneshshettyin sir please  review it 
And check size is ok now or not then I will fix the position of moon and sun

**Comment by arpit456jain** [comment]
@vigneshshettyin sir here is the video 

https://user-images.githubusercontent.com/55352601/112752007-72721680-8fee-11eb-857a-0ace5241ff39.mp4

**Comment by arpit456jain** [comment]
@vigneshshettyin sir size is fine ?  or I should decrease it more?

**Comment by arpit456jain** [comment]
@shades-7 please review this PR.

If any further changes has to be done.
Its size can be decreased more but then it may be very small for phone view.
If you want i can try to minimise it more.
Please let me know.🙂

**Comment by arpit456jain** [comment]
@vigneshshettyin sir is it ok ? or should I try to decrease more.

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin sir is it ok ? or should I try to decrease more.

Hey, @arpit456jain our project mentor @shades-7 will check your pr.

**Comment by arpit456jain** [comment]
> > @vigneshshettyin sir is it ok ? or should I try to decrease more.
> 
> Hey, @arpit456jain our project mentor @shades-7 will check your pr.

Ok no problem

**Comment by shades-7** [comment]
> @shades-7 please review this PR.
> 
> If any further changes has to be done.
> Its size can be decreased more but then it may be very small for phone view.
> If you want i can try to minimise it more.
> Please let me know.

hello, @arpit456jain good work :partying_face: 
 but I will suggest decreasing size a bit more for the desktop version and for the phone version write another CSS in media query so that it's not very small for a phone.

and if possible also fix the size of the moon and sun.
thank you :+1:

**Comment by arpit456jain** [comment]
Ok @shades-7 I will do it by 5 pm today.

**Comment by arpit456jain** [comment]
@vigneshshettyin sir I just pull the latest code and trying to commit it but some issue occur so I git clone the repo again.
And I found this issue again. Is it ok ??
s

**Comment by arpit456jain** [comment]
@vigneshshettyin due to conflicts I am closing this PR and will create a fresh PR after doing the work again.

**Comment by arpit456jain** [comment]
> @vigneshshettyin due to conflicts I am closing this PR and will create a fresh PR after doing the work again.

#169

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin sir I just pull the latest code and trying to commit it but some issue occur so I git clone the repo again.
> And I found this issue again. Is it ok ??
> s

Yes, it is fine. @arpit456jain

**Comment by arpit456jain** [comment]
ok @vigneshshettyin kindly review my fresh PR #169

**Comment by vigneshshettyin** [comment]
Hey, @arpit456jain I had told you earlier as well all design changes will be approved by @shades-7

**Comment by arpit456jain** [comment]
@vigneshshettyin yes sir I know I just mention you for knowing your view on this. what do you think is it fine now or not?

**Pull request closed without merging**
