### PR TITLE
deployment of project to different cloud platforms like Digital Ocean

### LINKED ISSUE #304: Add documentation for different app platforms
### Is your feature request related to a problem? Please describe.
The project is currently deployed on Heroku. However, it is possible to deploy it on app platforms like Digital Ocean/Heroku, etc. So there is a need to include documentation on how to do that in the repository. 

### Describe how this feature will be useful to our readers.
It will help people to get a better understanding of the project as well as know how to deploy it on the platform of their choice.

<hr/>

Note:  
If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment and wait for the maintainer or a mentor to assign it to you. Then you can create a PR.

### PR DESCRIPTION
**Pull request by subhangi2731**
## Related Issue 
Added Documentation and steps for deploying the project to Digital Ocean Platform

- Info about the related issue 
Closes: #304 

### Describe the changes you've made
I have made the documentation on how can we deploy our project to Digital Ocean platform

## Type of change

What sort of change have you made:

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Code style update (formatting, local variables)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by vigneshshettyin — COMMENTED** [review]
Hey, @APratham  & @shades-7 pls review this PR.

**Comment by subhangi2731** [comment]
@shades-7 @APratham please review and merge my pr

**Review by shades-7 — CHANGES_REQUESTED** [review]
Everything seems fine, just remove the Google_cloud.md and Azure.md cause this issues is not related to them

**Review by APratham — APPROVED** [review]
Great work @subhangi2731!

**Comment by APratham** [comment]
Merged 3a18928 to main

**Comment by subhangi2731** [comment]
@APratham thank u so much for ur support and guidance. Did u merge all the 3 prs because some changes were requested to delete the other file from branch so I was updating the branch but i see the pr has been closed .

**Comment by subhangi2731** [comment]
@APratham @shades-7 @vigneshshettyin I have updated my branch by deleting the other 2 files from this digital ocean branch. please merge the 3 prs

**Comment by APratham** [comment]
@subhangi2731 Please see my comment. I didn't merge the PR, I merged the commit. So you don't need to delete the files. I had to do it because in one PR you had added all 3 files. Please make sure this doesn't happen for future PRs 🙂

One way you can accomplish that is by creating separate branches on your repo and not creating the PR from main

**Comment by subhangi2731** [comment]
@APratham i am sorry it was by mistake i created the other 2 files in this specific branch but i had pushed the 3 prs from 3 different branches to main. So I dont have to send another pr? these 3 commits are merged to main right?

**Comment by APratham** [comment]
Yes all have been merged, no need to worry. But please don't do that for future PRs. Not just this repo, but elsewhere too

**Comment by subhangi2731** [comment]
@APratham yes I will not do this again will take care of this doesn't happen again

**Comment by subhangi2731** [comment]
@APratham @shades-7 @vigneshshettyin the 3 prs which I made today I have not been given scores for this 3 prs the leaderboard has been updated now but I see I have not been given scores for this can I again raise prs for these 3 issues please reply

**Comment by subhangi2731** [comment]
@APratham @vigneshshettyin @shades-7 please revert the merge so that I will send the pr once again on these 3 issues

**Pull request closed without merging**
