### PR TITLE
steps for deployment of project to Google Cloud

### LINKED ISSUE #302: Add documentation for different cloud platforms | Google Cloud
### Is your feature request related to a problem? Please describe.
The project is currently deployed on Heroku. However, it is possible to deploy it on other cloud platforms too, like GCP, AWS, Digital Ocean, etc. So there is a need to include documentation on how to do that in the repository. 

### Describe how this feature will be useful to our readers.
It will help people to get a better understanding of the project as well as know how to deploy it on the platform of their choice.

<hr/>

Note:  
If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment and wait for the maintainer or a mentor to assign it to you. Then you can create a PR.

### PR DESCRIPTION
**Pull request by subhangi2731**
## Related Issue 
Made documentation on steps for how to deploy your project on Google Cloud Engine

- Info about the related issue 

Closes: #302 

### Describe the changes you've made
I have added all the steps of deployment of project repository to google cloud engine

## Type of change

What sort of change have you made:

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Code style update (formatting, local variables)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by subhangi2731** [comment]
@vigneshshettyin  please review and merge my pr

**Review by vigneshshettyin — COMMENTED** [review]
Hey, @APratham  & @shades-7 pls review this PR.

**Comment by subhangi2731** [comment]
@shades-7 @APratham please review and merge my pr

**Review by shades-7 — APPROVED** [review]
Good work :100:  @subhangi2731

**Comment by subhangi2731** [comment]
@shades-7 thank u so much

**Comment by APratham** [comment]
Merged acd3cf9 into main

**Pull request closed without merging**
