### PR TITLE
[Gssoc'21] Fix the decrease the size of toggle button

### LINKED ISSUE #158: [Gssoc'21] Size of dark mode toggle is too big
### **Describe the bug**
Size of dark mode toggle is too big
### **Expected behavior**
Its size should be decrease little bit in Desktop view and little bit more for phone view

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

The size of toggle button was very big.

Closes: #158 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change
I am attaching a video in next comment.  
What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Code style update (formatting, local variables)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [] Any dependent changes have been merged and published in downstream modules.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/112984962-2ef9e280-917d-11eb-8744-ac811b18b69b.mp4

@vigneshshettyin @shades-7 please review this PR Its  a fresh PR for same issue due to conflicts I have to close that PR and pull latest code and done some changes again.

I had decreased the size as much as possible in both version Its not possible to decrease more .
Kindy add labels of gssoc'21 and level3(if possible)  before merging.
And Kindly Merge it.

**Comment by arpit456jain** [comment]
@shades-7 if you still think the size is large I can try to find any new toggle button but for now it is perfect for me.

**Review by shades-7 — COMMENTED** [review]
Everything looks perfect. Thanks for your contribution just look why your checks have failed and fix it

**Comment by shades-7** [comment]
Screenshot_20210330-223742_Chrome
Try to write clean and good code.
 * Use hexadecimal value for colours
 * write 0px instead of 0
 These are small changes but good practice

**Comment by arpit456jain** [comment]
@shades-7  i had not written these css these are already there i had written darkmode.css

**Comment by shades-7** [comment]
> @shades-7 i had not written these css these are already there i had written darkmode.css

Okay thanks for bringing it to our notice, can you look why your checks are failed

**Comment by arpit456jain** [comment]
@vigneshshettyin can you help me out what should i do?

**Comment by arpit456jain** [comment]
> > @shades-7 i had not written these css these are already there i had written darkmode.css
> 
> Okay thanks for bringing it to our notice, can you look why your checks are failed

Yes i can give m 5 min but i am not giving any gurrentie that all checks will pass but i will try to make it possible to pas as much as possible

**Comment by arpit456jain** [comment]
Untitled2

@shades-7 mam due to this type of css these issue are occurring.

**Comment by arpit456jain** [comment]
In many places duplicates values are given .
@shades-7 I had a suggestion/request 
Merge it for now tomorrow  I will create a issue for this and will solve these conflicts as much as possible because its not right to change the CSS now it can cause harm to website.

**Comment by arpit456jain** [comment]
Untitled3

There are a lot of issues like this. It will take time to solve all these. I think some-one writes these css in a little bit hurry.

**Comment by arpit456jain** [comment]
@shades-7 please add labels of GSSoC'21 and if possible (level 3) before merging.

**Comment by shades-7** [comment]
> @shades-7 please add labels of GSSoC'21 and if possible (level 3) before merging.

Hello, @arpit456jain I understand you want to earn as many points as you can and get many PRs merged but this is not how things run please also focus on getting issues solved.
@vigneshshettyin some checks are failed apart from that everything is fine, please look into this

**Comment by arpit456jain** [comment]
Thanks @vigneshshettyin , can  I create a new issue for resolving the problem with style.css?

**Comment by vigneshshettyin** [comment]
> Thanks @vigneshshettyin , can  I create a new issue for resolving the problem with style.css? 

Yes @arpit456jain

**Pull request merged**
