### PR TITLE
Bug in Register page 

### LINKED ISSUE #140: Bug in Register page
### **Describe the bug**
There is bug or I should say (something irritating) in register page in password fields.
When I enter password it flashes the error which is ok.
but because of this error the whole page got affected for sec which is very irritating, at-least for me
I want solve this issue

I am attaching a  video for better understanding of my issue.

https://user-images.githubusercontent.com/55352601/112672455-82bcb100-8e89-11eb-8c19-063c4ab7fbb5.mp4

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

- Info about the related issue 
There was bug  in register page in error flashing area below password fields.
When I enter password it flashes the error which is ok.
but because of this error the whole page got affected for sec which is very irritating, at-least for me
Closes: #140 

### Describe the changes you've made
I am attaching a video for better understanding my changes.
https://user-images.githubusercontent.com/55352601/112710272-cf35da00-8ee5-11eb-9139-af5ae8c56bf5.mp4

**now the error message flashes but it doesn't effect the whole page**

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Code style update (formatting, local variables)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.
- [] Any dependent changes have been merged and published in downstream modules.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by arpit456jain** [comment]
@shades-7 please add labels before merging.

**Comment by arpit456jain** [comment]
@shades-7 I had remove the console comments from darkmode.js and toggle button since I was who added that feature(darkmode and toggle button) , I just had forgot to remove them.

**Review by shades-7 — CHANGES_REQUESTED** [review]
@arpit456jain in the video you have provided we still see the message below the password flickering, can you fix that

**Comment by arpit456jain** [comment]
> @arpit456jain in the video you have provided we still see the message below the password flickering, can you fix that

for now I am not able to fix that , **It is the feature added by someone it activate when user enter something every time **
first of all I had tried to solve that It takes me 2 hours but that won't work well so at the end I had added some extra space for it so it won't effect the whole page.

@shades-7  For now please merge it, **if possible** and add labels of gssoc'21 .

**Comment by shades-7** [comment]
@arpit456jain sorry we can't merge it until the issue is completely fixed, if you want to continue its good, if not let us know we will assign it to someone else

**Comment by arpit456jain** [comment]
@shades-7 please assign it to someone else.

**Comment by vigneshshettyin** [comment]
> @shades-7 please assign it to someone else.

We will be closing this pr for now. Kindly decrease the size of the dark mode button you have added it's too big.  @arpit456jain

**Comment by arpit456jain** [comment]
> > @shades-7 please assign it to someone else.
> 
> We will be closing this pr for now. Kindly decrease the size of the dark mode button you have added it's too big. @arpit456jain

ok sir I will try to do it in a new issue.

**Comment by arpit456jain** [comment]
@vigneshshettyin  sir according to me 
Error flashing is not an issue its a feature which was added by someone and it was working fine.
According to me the bug is it is affecting the whole page which is irritating. 
The rest that you think is right. I have no issues 🙂

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin  sir according to me 
> Error flashing is not an issue its a feature which was added by someone and it was working fine.
> According to me the bug is it is affecting the whole page which is irritating. 
> The rest that you think is right. I have no issues 🙂
> 

We will try to fix it. If you any thoughts as in how to fix. Please mention in issue created. @arpit456jain

**Comment by arpit456jain** [comment]
We can remove that feature 😅 by removing js
It will not flash error messages.
Just a suggestion!! Don't get me wrong 😅.



Because its very hard to fix it for me for now.😅

**Comment by vigneshshettyin** [comment]
> We can remove that feature 😅 by removing js
> It will not flash error messages.
> Just a suggestion!! Don't get me wrong 😅.
> 
> Because its very hard to fix it for me for now.😅

Cool no issues, We will figure some way out anyway. Thanks for contributing @arpit456jain

**Comment by arpit456jain** [comment]
@vigneshshettyin sir I just got another idea.
We can flash error or success message by use of python in backend like i had done form validation in contact us form in main page.
We can remove js from here and python will take care of  all the validation.
In this case error messages will flash only when user try to submit and something is wrong.

**Comment by arpit456jain** [comment]
> @vigneshshettyin sir I just got another idea.
> We can flash error or success message by use of python in backend like i had done form validation in contact us form in main page.
> We can remove js from here and python will take care of all the validation.
> In this case error messages will flash only when user try to submit and something is wrong.

Like this

https://user-images.githubusercontent.com/55352601/112722710-1b5a3c00-8f31-11eb-8d28-d49d4f8a5a6e.mp4

**Comment by arpit456jain** [comment]
> > @vigneshshettyin sir I just got another idea.
> > We can flash error or success message by use of python in backend like i had done form validation in contact us form in main page.
> > We can remove js from here and python will take care of all the validation.
> > In this case error messages will flash only when user try to submit and something is wrong.
> 
> Like this
> 
>  2021-03-27.19-15-58.mp4

@vigneshshettyin sir how's this.

**Comment by vigneshshettyin** [comment]
@arpit456jain That's great but as a developer, to decrease the load on the server, we should implement validation part using frontend-only this is considered to be the best practice.

**Comment by arpit456jain** [comment]
> @arpit456jain That's great but as a developer, to decrease the load on the server, we should implement validation part using frontend-only this is considered to be the best practice.

ok sir got it. I will think on it.

**Comment by vigneshshettyin** [comment]
> > @arpit456jain That's great but as a developer, to decrease the load on the server, we should implement validation part using frontend-only this is considered to be the best practice.
> 
> ok sir got it. I will think on it.

Great, Thanks for contributing! @arpit456jain

**Comment by arpit456jain** [comment]
> @arpit456jain That's great but as a developer, to decrease the load on the server, we should implement validation part using frontend-only this is considered to be the best practice.

Its 3 30 am 😅 I was thinking about this so i start searching on Google about that and after a 1 hour searching finally i found something cool 😎

**Comment by arpit456jain** [comment]
> > @arpit456jain That's great but as a developer, to decrease the load on the server, we should implement validation part using frontend-only this is considered to be the best practice.
> 
> I was thinking about this so i start searching on Google about that and after a 1 hour searching finally i found something cool 😎

@vigneshshettyin sir how is it now.

https://user-images.githubusercontent.com/55352601/112736040-b248e780-8f75-11eb-9375-35572b1756c8.mp4

**Comment by vigneshshettyin** [comment]
Hey, @arpit456jain this is really cool just a small suggestion add a condition for password matching as well. You can make a pr for this. Raise a new issue then proceed.

**Comment by arpit456jain** [comment]
@vigneshshettyin ok sir sure

**Pull request closed without merging**
