### PR TITLE
[Gssoc'21] Fix the Bug in Register page.

### LINKED ISSUE #140: Bug in Register page
### **Describe the bug**
There is bug or I should say (something irritating) in register page in password fields.
When I enter password it flashes the error which is ok.
but because of this error the whole page got affected for sec which is very irritating, at-least for me
I want solve this issue

I am attaching a  video for better understanding of my issue.

https://user-images.githubusercontent.com/55352601/112672455-82bcb100-8e89-11eb-8c19-063c4ab7fbb5.mp4

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

There is bug or I should say (something irritating) in register page in password fields.
When I enter password it flashes the error which is ok.
but because of this error the whole page got affected for sec which is very irritating
previously the register page is looking like this

https://user-images.githubusercontent.com/55352601/112746311-9b34e480-8fcb-11eb-97d8-2ec9a9917c0f.mp4

Closes: #140 

### Describe the changes you've made

I had removed that js and added new js in it and added password validations.
Please watch this video for better understanding.

https://user-images.githubusercontent.com/55352601/112746373-f1098c80-8fcb-11eb-850b-5fc697525462.mp4

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [] Any dependent changes have been merged and published in downstream modules.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by arpit456jain** [comment]
@vigneshshettyin sir I had pull the latest code and done the password validations.
I had also added confirm password validation as you told.
**In addition to that I had also disabled the submit button I will enable automatically when all the password validations pass**

**Comment by vigneshshettyin** [comment]
Thanks for contributing @arpit456jain!

**Comment by arpit456jain** [comment]
@vigneshshettyin thank you sir

**Comment by vigneshshettyin** [comment]
Hey, @arpit456jain kindly decrease the size of dark mode button and make a pr.

**Comment by arpit456jain** [comment]
@vigneshshettyin ok I will start work on it as soon as possible

**Pull request merged**
