### PR TITLE
add instructions.md

### PR DESCRIPTION
**Pull request by khareyash05**
With reference to issue #44 
Added the following with steps
1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream

### CODE REVIEW

**Review by shades-7 — CHANGES_REQUESTED** [review]
Everything seems fine @khareyash05 just add how to use the templates and edit the PR description too using a template and its good to go

**Comment by khareyash05** [comment]
Hey @shades-7 I am not able to edit the PR description according to PR template. THose checkboxes arent coming up.

**Review by shades-7 — APPROVED** [review]
@khareyash05 Thank you so much for your contribution 🥳

**Comment by khareyash05** [comment]
@shades-7 Thanx to you too .

**Comment by khareyash05** [comment]
@shades-7 Could you pls add a level label and a GSSOC label to the PR ?
Thanx

**Comment by shades-7** [comment]
Labels are assigned to issues that GSSOC'21 label is there.

**Comment by khareyash05** [comment]
@shades-7  Could you pls add a level label and a GSSOC label to the PR as well because adding a level label to the PR is only being counted
Thanx!

**Comment by khareyash05** [comment]
@shades-7 Could you pls add a level label and a GSSOC label to the PR as well because adding a level label to the PR is only being counted
Thanx!

**Pull request merged**
