### PR TITLE
[Gssoc'21] Added show password feature

### LINKED ISSUE #163: [Gssoc'21] Add a show password button
I want to Add a show password **[checkbox]** button
because when I am creating a password there is chance I got forget what I type in password field
then it is very difficult for anyone to enter same password in both or may be any wrong key got pressed.

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] GSSOC21
- [] Any other

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

- Info about the related issue 
There was no show password button that's why sometimes its very hard to sign up of login

Closes: #163 

### Describe the changes you've made

https://user-images.githubusercontent.com/55352601/113144462-e3156f00-924a-11eb-9dcf-ed9191539faf.mp4

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Code style update (formatting, local variables)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [] Any dependent changes have been merged and published in downstream modules.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by arpit456jain** [comment]
@vigneshshettyin  I don't understand why it is saying function was declared but never used😅😅
May be because they will get active when user ✅ the checkbox 🤔 kindly guide me how to resolve this issue

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin I don't understand why it is saying function was declared but never used😅😅
> May be because they will get active when user ✅ the checkbox 🤔 kindly guide me how to resolve this issue

Just ignore it @arpit456jain .
Thanks for contributing!

**Comment by arpit456jain** [comment]
@vigneshshettyin can you please guide me how to access database like when i use mysql i can run xamp and can go to phpnyadmin and access all the data .
In django i can go into admin by creating superuser .
How to access in this project?

**Pull request merged**
