### PR TITLE
added a  link to read me

### LINKED ISSUE #334: testing the github action of greeting
testing the github action of greeting

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

added a  link to read me 

Closes: #334 

### Describe the changes you've made
just replace a link

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Code style update (formatting, local variables)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [] Any dependent changes have been merged and published in downstream modules.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Review by vigneshshettyin — APPROVED** [review]

**Comment by arpit456jain** [comment]
@vigneshshettyin please add labels so i can check if its ok or not

**Comment by vigneshshettyin** [comment]
> check if its ok or not

Which labels do you want me to add @arpit456jain

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly add gssoc and level0 label

**Comment by arpit456jain** [comment]
yeah its working fine

**Pull request merged**
