### PR TITLE
added content about routes of the available endpoints

### LINKED ISSUE #385: Doing the Routing part for the React App
I will provide the routes for the react setup app

### PR DESCRIPTION
**Pull request by subhangi2731**
## Related Issue 

- added content about routes of the available endpoints in the project in the homepage

Closes: #385 

### Describe the changes you've made

Made routes.js and added content about various routes which can be used to access endpoints

## Type of change

What sort of change have you made:

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Code style update (formatting, local variables)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by vigneshshettyin** [comment]
> ## Related Issue
> * added content about routes of the available endpoints in the project in the homepage
> 
> Closes: #385
> 
> ### Describe the changes you've made
> Made routes.js and added content about various routes which can be used to access endpoints
> 
> ## Type of change
> What sort of change have you made:
> 
> * [] Bug fix (non-breaking change which fixes an issue)
> * [x]  New feature (non-breaking change which adds functionality)
> * [] Code style update (formatting, local variables)
> * [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [] This change requires a documentation update
> 
> ## Mention any unusual behaviour of your code (Write NA if not)
> NA
> 
> ## Checklist:
> * [x]  My code follows the guidelines of this project.
> * [x]  I have performed a self-review of my own code.
> * [x]  I have commented my code, particularly whereever it was hard to understand.
> * [x]  My changes generate no new warnings.
> * [x]  Any dependent changes have been merged and published in downstream modules.

Please attach screenshots of the working app @subhangi2731

**Comment by subhangi2731** [comment]
Screenshot from 2021-05-25 19-38-34
Screenshot from 2021-05-25 19-38-44
Screenshot from 2021-05-25 19-38-48

**Comment by subhangi2731** [comment]
@vigneshshettyin this is the working app I made in reactjs where I have used the class , function component and state object with props as the argument and then I have given navigation links to switch the pages and routes for available endpoints which have been used in the project

**Comment by subhangi2731** [comment]
please see and merge my pr

**Pull request merged**
