### PR TITLE
done the whole react setup

### LINKED ISSUE #358: Adding React to the project
Add React for front-end development. Setting up a frontend folder with boilerplate code.

### PR DESCRIPTION
**Pull request by subhangi2731**
## Related Issue 

- Adding React to the project and doing the whole react setup and installing the required dependencies by adding package.json, package.lock.json as it happens by setting the react app , readme file and adding .gitignore then moving on to react files in docs/src 

Closes: #358 

### Describe the changes you've made

I have added react files in docs/src which are App.css, App.js, App.test.js, Index.js, Index.css, logo.svg, reportWebVitals.js, setupTests.js then in public folder is favicon, index.hrml, logos, manifest.json and robots.txt

## Type of change

What sort of change have you made:

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Code style update (formatting, local variables)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

## Additional Info (optional)
I have done the whole react setup and installed its packages , dependencies and files

### CODE REVIEW

**Comment by subhangi2731** [comment]
@vigneshshettyin please review and merge I have also done the documentation part in README.md

**Review by vigneshshettyin — APPROVED** [review]

**Comment by shades-7** [comment]
@subhangi2731 You have just added the basic react boilerplate it will be great if you will set up the basic routing too

**Comment by vigneshshettyin** [comment]
> @subhangi2731 You have just added the basic react boilerplate it will be great if you will set up the basic routing too

And please do switch branch and commit don't commit to main. @subhangi2731

**Comment by subhangi2731** [comment]
hey @shades-7 I will do the routing part too also in separate issue as it is a huge one and a separate issue needs to created for that

**Pull request merged**
