### PR TITLE
Added hover effect to buttons

### LINKED ISSUE #79: Add hover effect to buttons
### Is your feature request related to a problem? Please describe.
Add hover effects to send message and submit feedback button.

### Describe the solution you'd like
As we can see that every button in site has hover effect, but two buttons are lacking of it. So i would like to add it.

### Which Program are you part of?

- [x] GSSOC21

### PR DESCRIPTION
**Pull request by Aayush-hub**
## Related Issue 

- Added hover effect to submit feedback and send message buttton

Closes: #79 

## Type of change

What sort of change have you made:

- [x] Code style update (formatting, local variables)

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by shades-7 — COMMENTED** [review]
@Aayush-hub can you please add any screenshots or gifs so that we can see them?

**Comment by Aayush-hub** [comment]
> @Aayush-hub can you please add any screenshots or gifs so that we can see them?
@shades-7 
sample gif

**Review by shades-7 — APPROVED** [review]
@Aayush-hub Thanks for your contribution :+1:

**Comment by vigneshshettyin** [comment]
@all-contributors please add @Aayush-hub for design

**Pull request merged**
